platform:ios, '8.0'
use_frameworks!
target'All For Basketball' do

pod 'Alamofire', '~> 4.4.0'
pod 'SnapKit', '~> 3.2.0'
pod 'Kingfisher', '~> 3.6.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'SwiftyJSON', '~> 3.1.4'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'RealReachability', '~> 1.1.8'

end
